### ISSUE TITLE
Create app.py

### ISSUE THREAD

**Issue by youngilkim822** [PromoSquad/promotions#44]
**As a** developer
**I need** app.py 
**So that** I can run flask

**Details & Assumptions:** 
In terminal for instance, type following command line:
**python app.py** and if we access through **localhost:5000** or **127.0.0.1:5000**, 
then we can see the web page working

**Acceptance Criteria:**

```gherkin
Given [some initial state]
When we run app.py
Then we can see all the web page for the promotion
```

**Comment by timtitan180** [comment]
Hello. In order to get your page loaded in the browser from your app.py app.py you can try something like this:

`from flask import Flask, request, render_template, url_for, redirect, session`

`app = Flask(__name__)`



`@app.route('/your_home_route', methods=["GET"])
def home_route():
//your code here
    return render_template("index.html", datestamp=date)

//post method 
@app.route('/your_post_route', methods=['GET', 'POST'])
def post_route():
    if request.method == "POST":
  //Your code here
                return render_template("index.html", errors=errors, pdf_analysis=analysis,datestamp=date)

//run app.py in your terminal then go to your browser and do http:localhost:
if __name__ == "__main__":
    app.run(debug=True, PORT=5000(or another port you choose)`

from your terminal write the command python app.py to run the flask server then go to your browser and see your application by doing http:localhost:5000/(the route you wrote in the get method or leave blank if you just left the '/').

Hope this helps!
